version: '3,8'

services: 
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongodb
    hostname: host-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: master
    volumes:
      - ./data:/data/db
      - ./data/log:/var/log/mongodb/
    ports:
      - "27017:27017"